# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20180927_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='location',
            name='description',
        ),
    ]
